version: '3.8'

services:
  kotlin-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    networks:
      - kotlin-network
    restart: always

networks:
  kotlin-network:
    driver: bridge