spring:
  application:
    name: shop
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/mydb;MODE=PostgreSQL
    username: sa
    password:
  flyway:
    enabled: true
    user: sa
    password:
    url: jdbc:h2:file:./data/mydb;MODE=PostgreSQL
    locations: classpath:db/migration
    schemas: public
  jpa:
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org:
      springframework:
        core:
          env: DEBUG
      flywaydb: DEBUG